=== clg55/Scilab-Workbench/browsable_source/2.6-en/Unix-Windows/scilab-2.6-en/packages/stixbox-1.2.3/man/man.dtd
<!ELEMENT MAN (META?,LANGUAGE,TITLE,TYPE,DATE,SHORT_DESCRIPTION*,KEYWORD?,CALLING_SEQUENCE?,PARAM*,DESCRIPTION?,ITEMIZE*,EXAMPLE?,SEE_ALSO?,AUTHOR?,BIBLIO?,USED_FUNCTIONS?)>
<!ELEMENT META (#PCDATA)  	 >

<!ATTLIST META 
PATH 	CDATA 	"SCI/" 
CATEGORY 	CDATA 	"ScilabFunction" 	 
VERSION_SCI 	CDATA 	"2.6" 	 
VERSION_DOC 	CDATA 	"1.0" 	 
AUTHOR 	CDATA 	"Matthieu PHILIPPE" 	 
 >

<!ELEMENT LANGUAGE (#PCDATA)  	 >

<!ELEMENT TITLE (#PCDATA)  	 >

<!ELEMENT DATE (#PCDATA)  	 >

<!ELEMENT TYPE (#PCDATA)  	 >

<!ELEMENT KEYWORD (#PCDATA)  	 >

<!ELEMENT SHORT_DESCRIPTION (#PCDATA | P|PP)*  	 >

<!ATTLIST SHORT_DESCRIPTION name CDATA #REQUIRED  	 >

<!ELEMENT USED_FUNCTIONS (#PCDATA)  	 >

<!ELEMENT CALLING_SEQUENCE (#PCDATA|PP|CALLING_SEQUENCE_ITEM)*  	 >

<!ELEMENT PARAM (#PCDATA|PARAM_ITEM|PARAM_INDENT|ITEMIZE|P|TABLE|PP)*  	 >

<!ATTLIST PARAM target (out|in) #IMPLIED  	 >

<!ELEMENT PARAM_ITEM ((PARAM_NAME,PARAM_DESCRIPTION,PARAM_ITEM*)|PARAM_INDENT*)  	 >

<!ELEMENT PARAM_NAME (#PCDATA|VERB)*  	 >

<!ELEMENT PARAM_DESCRIPTION (#PCDATA|P|PP|TABLE|PARAM_INDENT|VERB)*  	 >

<!ELEMENT PARAM_INDENT (#PCDATA|PARAM_ITEM|PARAM_INDENT|P|PP|TABLE|VERB|VERBATIM)*  	 >

<!ELEMENT DESCRIPTION (#PCDATA|P|PP|TABLE|DESCRIPTION_ITEM|VERB|VERBATIM|LINK)*  	 >

<!ELEMENT DESCRIPTION_ITEM (#PCDATA|P|PP|TABLE|ITEMIZE|VERB)*  	 >

<!ATTLIST DESCRIPTION_ITEM label CDATA #IMPLIED  	 >

<!ELEMENT EXAMPLE (#PCDATA)  	 >

<!ELEMENT SEE_ALSO (SEE_ALSO_ITEM)+  	 >

<!ELEMENT AUTHOR (#PCDATA)  	 >

<!ELEMENT BIBLIO (#PCDATA)  	 >

<!ELEMENT CALLING_SEQUENCE_ITEM (#PCDATA)  	 >

<!ELEMENT SEE_ALSO_ITEM (#PCDATA|P|A|LINK)*  	 >

<!ELEMENT A (#PCDATA)*  	 >

<!ATTLIST A href CDATA #REQUIRED  	 >

<!ELEMENT LINK (#PCDATA)*  	 >

<!ELEMENT P (#PCDATA|TABLE|ITEM|EMPTY|VERB|A|LINK)*  	 >

<!ELEMENT VERBATIM (#PCDATA)  	 >

<!ELEMENT ITEM (#PCDATA|TABLE|ITEM|P|VERB)*  	 >

<!ATTLIST ITEM label CDATA #IMPLIED  	 >

<!ELEMENT ITEMIZE (TABLE|ITEM|P|VERBATIM)*  	 >

<!ATTLIST ITEMIZE label CDATA #IMPLIED  	 >

<!ELEMENT TABLE (TABLE_NEW_ROW)+  	 >

<!ELEMENT TABLE_NEW_ROW (TABLE_NEW_COLUMN)+  	 >

<!ELEMENT TABLE_NEW_COLUMN (#PCDATA|VERB)*  	 >

<!ELEMENT MATH (#PCDATA ) 	 >

<!ELEMENT VERB (#PCDATA )>

<!ELEMENT REMARKS (#PCDATA )>

=== clg55/Scilab-Workbench/browsable_source/2.7/Linux/scilab-2.7/man/eng/graphics/black.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?> 
<!DOCTYPE MAN SYSTEM "../../man.dtd">
<MAN>
  <LANGUAGE>eng</LANGUAGE>
  <TITLE>black  </TITLE>
  <TYPE>Scilab Function  </TYPE>
  <DATE>April 1993  </DATE>
  <SHORT_DESCRIPTION name="black"> Black&apos;s diagram (Nichols chart)  </SHORT_DESCRIPTION>
  <CALLING_SEQUENCE>
  <CALLING_SEQUENCE_ITEM>black( sl,[fmin,fmax] [,step] [,comments] )  </CALLING_SEQUENCE_ITEM>
  <CALLING_SEQUENCE_ITEM>black( sl,frq [,comments] )  </CALLING_SEQUENCE_ITEM>
  <CALLING_SEQUENCE_ITEM>black(frq,db,phi [,comments])  </CALLING_SEQUENCE_ITEM>
  <CALLING_SEQUENCE_ITEM>black(frq,repf  [,comments])   </CALLING_SEQUENCE_ITEM>
  </CALLING_SEQUENCE>
  <PARAM>
 <PARAM_INDENT>
  <PARAM_ITEM>
  <PARAM_NAME>sl  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : list ( linear system <VERB>syslin</VERB>)
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
  <PARAM_ITEM>
  <PARAM_NAME>fmin,fmax  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : real scalars (frequency bounds)
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
  <PARAM_ITEM>
  <PARAM_NAME>frq  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : row vector or matrix (frequencies)
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
  <PARAM_ITEM>
  <PARAM_NAME>db,phi  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : row vectors or matrices (modulus, phase)
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
  <PARAM_ITEM>
  <PARAM_NAME>repf  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : row vectors or matrices (complex frequency response)
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
  <PARAM_ITEM>
  <PARAM_NAME>step  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : real
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
  <PARAM_ITEM>
  <PARAM_NAME>comments  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : string
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
 </PARAM_INDENT>
  </PARAM>
  <DESCRIPTION>
  <P>
    Black&apos;s diagram (Nichols&apos;chart) for a linear system <VERB>sl</VERB>.
    <VERB>sl</VERB> can be a continuous-time or discrete-time SIMO system (see <VERB>syslin</VERB>).
    In case of multi-output the outputs are plotted with different
    symbols.
  </P>
  <P>
  </P>
  <P>
    The frequencies are given by the bounds <VERB>fmin,fmax</VERB> (in Hz) or by a row-vector
    (or a matrix for multi-output) <VERB>frq</VERB>.
  </P>
  <P>
  </P>
  <P>
    <VERB>step</VERB> is the ( logarithmic ) discretization step. (see <VERB>calfrq</VERB> for the
    choice of default value).
  </P>
  <P>
  </P>
  <P>
    <VERB>comments </VERB> is a vector of character strings (captions).
  </P>
  <P>
  </P>
  <P>
    <VERB>db,phi</VERB> are the matrices of modulus (in Db) and phases (in degrees). 
    (One row for each response).
  </P>
  <P>
  </P>
  <P>
    <VERB>repf </VERB> matrix of complex numbers. One row for each response.
  </P>
  <P>
  </P>
  <P>
    To plot the grid of iso-gain and iso-phase of <VERB>y/(1+y)</VERB> use <VERB>chart()</VERB>.
  </P>
  <P>
  </P>
  <P>
    Default values for <VERB>fmin</VERB> and <VERB>fmax</VERB> are
    <VERB>1.d-3</VERB>, <VERB>1.d+3</VERB> if <VERB>sl</VERB> is continuous-time
    or <VERB>1.d-3</VERB>, <VERB>0.5</VERB> if <VERB>sl</VERB> is discrete-time.
  </P>
  </DESCRIPTION>
  <EXAMPLE><![CDATA[
s=poly(0,'s')
h=syslin('c',(s^2+2*0.9*10*s+100)/(s^2+2*0.3*10.1*s+102.01))
chart();
sstr='(s^2+2*0.9*10*s+100)/(s^2+2*0.3*10.1*s+102.01)';
black(h,0.01,100,sstr);
h1=h*syslin('c',(s^2+2*0.1*15.1*s+228.01)/(s^2+2*0.9*15*s+225))
xbasc()
black([h1;h],0.01,100,['h1';'h'])
 ]]></EXAMPLE>
  <SEE_ALSO>
    <SEE_ALSO_ITEM> <LINK>bode</LINK> </SEE_ALSO_ITEM>     <SEE_ALSO_ITEM> <LINK>nyquist</LINK> </SEE_ALSO_ITEM>     <SEE_ALSO_ITEM> <LINK>chart</LINK> </SEE_ALSO_ITEM>     <SEE_ALSO_ITEM> <LINK>freq</LINK> </SEE_ALSO_ITEM>     <SEE_ALSO_ITEM> <LINK>repfreq</LINK> </SEE_ALSO_ITEM>     <SEE_ALSO_ITEM> <LINK>calfrq</LINK> </SEE_ALSO_ITEM>     <SEE_ALSO_ITEM> <LINK>phasemag</LINK> </SEE_ALSO_ITEM>
  </SEE_ALSO>
</MAN>

=== clg55/Scilab-Workbench/browsable_source/2.6-en/Unix-Windows/scilab-2.6-en/packages/stixbox-1.2.3/man/eng/stixbox/dchisq.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?> 
<!DOCTYPE MAN SYSTEM "../../man.dtd">
<MAN>
  <LANGUAGE>eng</LANGUAGE>
  <TITLE>dchisq  </TITLE>
  <TYPE>Stixbox Function  </TYPE>
  <DATE>Nov 2001  </DATE>
  <SHORT_DESCRIPTION name="dchisq"> The chisquare density function  </SHORT_DESCRIPTION>
  <CALLING_SEQUENCE>
  <CALLING_SEQUENCE_ITEM>f = dchisq(x,d)  </CALLING_SEQUENCE_ITEM>
  </CALLING_SEQUENCE>
  <PARAM>
 <PARAM_INDENT>
  <PARAM_ITEM>
  <PARAM_NAME>x  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : real
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
  <PARAM_ITEM>
  <PARAM_NAME>d  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : degree of freedom (x,d can be matrix with common size)
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
  <PARAM_ITEM>
  <PARAM_NAME>f  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : chisquare density function with d degree of freedom at the values of x 
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
 </PARAM_INDENT>
  </PARAM>
  <DESCRIPTION>
  <P>
    The chisquare density function
  </P>
  </DESCRIPTION>
</MAN>

=== clg55/Scilab-Workbench/browsable_source/2.6-en/Unix-Windows/scilab-2.6-en/man/fr/scicos/CLKSPLIT_f.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?> 
<!DOCTYPE MAN SYSTEM "../../man.dtd">
<MAN>
  <LANGUAGE>eng</LANGUAGE>
  <TITLE>CLKSPLIT_f  </TITLE>
  <TYPE>Scicos Block  </TYPE>
  <DATE>Janvier 1996  </DATE>
  <SHORT_DESCRIPTION name="CLKSPLIT_f"> Scicos event split block  </SHORT_DESCRIPTION>
  <DESCRIPTION>
  <P>
    This block is an event split block with an input and two outputs. The
    outputs reproduces the event the input port on each output ports. 
    Strictly speaking, CLKSPLIT is not a Scicos block because it is
    discarded at the compilation phase. This block is automatically
    created when creating a new link issued from a link.
  </P>
  <P>
    The inputs and output of CLKSPLIT are synchronized. 
  </P>
  </DESCRIPTION>
  <ITEMIZE label='DIALOGUE PARAMETERS'>
  <P>
    None.
  </P>
  </ITEMIZE>
</MAN>

=== clg55/Scilab-Workbench/browsable_source/2.7/Linux/scilab-2.7/man/eng/elementary/spones.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?> 
<!DOCTYPE MAN SYSTEM "../../man.dtd">
<MAN>
  <LANGUAGE>eng</LANGUAGE>
  <TITLE>spones  </TITLE>
  <TYPE>Scilab Function  </TYPE>
  <DATE>January 1995  </DATE>
  <SHORT_DESCRIPTION name="spones">  sparse matrix   </SHORT_DESCRIPTION>
  <CALLING_SEQUENCE>
  <CALLING_SEQUENCE_ITEM>sp=spones(A)  </CALLING_SEQUENCE_ITEM>
  </CALLING_SEQUENCE>
  <PARAM>
 <PARAM_INDENT>
  <PARAM_ITEM>
  <PARAM_NAME>A  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : sparse matrix
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
  <PARAM_ITEM>
  <PARAM_NAME>sp  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : sparse matrix
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
 </PARAM_INDENT>
  </PARAM>
  <DESCRIPTION>
  <P>
    <VERB>sp=spones(A)</VERB> generates a matrix with the same sparsity
    structure as <VERB>A</VERB>, but with ones in the nonzero positions;
  </P>
  </DESCRIPTION>
  <EXAMPLE><![CDATA[
A=sprand(10,12,0.1);
sp=spones(A)
B = A~=0
bool2s(B)
 ]]></EXAMPLE>
  <SEE_ALSO>
    <SEE_ALSO_ITEM> <LINK>sparse</LINK> </SEE_ALSO_ITEM>     <SEE_ALSO_ITEM> <LINK>full</LINK> </SEE_ALSO_ITEM>     <SEE_ALSO_ITEM> <LINK>eye</LINK> </SEE_ALSO_ITEM>     <SEE_ALSO_ITEM> <LINK>speye</LINK> </SEE_ALSO_ITEM>     <SEE_ALSO_ITEM> <LINK>spzeros</LINK> </SEE_ALSO_ITEM>
  </SEE_ALSO>
</MAN>

=== clg55/Scilab-Workbench/browsable_source/2.7/Linux/scilab-2.7/man/eng/fileio/oldload.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?> 
<!DOCTYPE MAN SYSTEM "../../man.dtd">
<MAN>
  <LANGUAGE>eng</LANGUAGE>
  <TITLE>oldload  </TITLE>
  <TYPE>Scilab Function  </TYPE>
  <DATE>April 1993  </DATE>
  <SHORT_DESCRIPTION name="oldload"> load saved variable in 2.4.1 and previous formats  </SHORT_DESCRIPTION>
  <CALLING_SEQUENCE>
  <CALLING_SEQUENCE_ITEM>oldload(&apos;file-name&apos; [,x1,...,xn])  </CALLING_SEQUENCE_ITEM>
  </CALLING_SEQUENCE>
  <PARAM>
 <PARAM_INDENT>
  <PARAM_ITEM>
  <PARAM_NAME>file-name  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : character string
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
  <PARAM_ITEM>
  <PARAM_NAME>xi  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : arbitrary Scilab variable name(s) given as strings.
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
 </PARAM_INDENT>
  </PARAM>
  <DESCRIPTION>
  <P>
    The <VERB>oldload</VERB> function is obsolete and is retained only for
    compatibility purpose.
  </P>
  <P>
    The <VERB>oldload</VERB> command can be used to reload in the Scilab session
    variables previously saved in a file with the <VERB>save</VERB> command.
  </P>
  <P>
    <VERB>oldload(&apos;file-name&apos;)</VERB> loads the variables saved in file <VERB>&apos;file-name&apos;</VERB>. 
  </P>
  <P>
    <VERB>oldload(&apos;file-name&apos;,&apos;x&apos;,&apos;y&apos;,...,&apos;z&apos;)</VERB> loads only variables <VERB>x,y,...,z</VERB>
    stored in file <VERB>&apos;file-name&apos;</VERB>. 
  </P>
  </DESCRIPTION>
  <EXAMPLE><![CDATA[
a=eye(2,2);b=ones(a);
oldsave(TMPDIR+'/vals.dat',a,b);
clear a
clear b
oldload(TMPDIR+'/vals.dat','a','b');
 ]]></EXAMPLE>
  <SEE_ALSO>
    <SEE_ALSO_ITEM> <LINK>save</LINK> </SEE_ALSO_ITEM>     <SEE_ALSO_ITEM> <LINK>getf</LINK> </SEE_ALSO_ITEM>
  </SEE_ALSO>
</MAN>

=== clg55/Scilab-Workbench/browsable_source/2.6-en/Unix-Windows/scilab-2.6-en/packages/stixbox-1.2.3/man/eng/stixbox/qqnorm.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?> 
<!DOCTYPE MAN SYSTEM "../../man.dtd">
<MAN>
  <LANGUAGE>eng</LANGUAGE>
  <TITLE>qqnorm  </TITLE>
  <TYPE>Stixbox Function  </TYPE>
  <DATE>Nov 2001  </DATE>
  <SHORT_DESCRIPTION name="qqnorm"> Normal probability paper  </SHORT_DESCRIPTION>
  <CALLING_SEQUENCE>
  <CALLING_SEQUENCE_ITEM>  qqnorm(x)  </CALLING_SEQUENCE_ITEM>
  <CALLING_SEQUENCE_ITEM>  qqnorm(x, symbol)  </CALLING_SEQUENCE_ITEM>
  </CALLING_SEQUENCE>
  <DESCRIPTION>
  <P>
    Normal probability paper. 
    Data on x-axis and  qnorm((i-1/2)/n)  on y-axis.
    The second optional argument is the plot symbol, e g &apos;+&apos;.
  </P>
  </DESCRIPTION>
  <SEE_ALSO>
    <SEE_ALSO_ITEM> <LINK>qqplot</LINK> </SEE_ALSO_ITEM>
  </SEE_ALSO>
</MAN>

=== clg55/Scilab-Workbench/browsable_source/2.6-en/Unix-Windows/scilab-2.6-en/man/fr/utilities/hex2dec.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?> 
<!DOCTYPE MAN SYSTEM "../../man.dtd">
<MAN>
  <LANGUAGE>fr</LANGUAGE>
  <TITLE>hex2dec  </TITLE>
  <TYPE>Scilab Function  </TYPE>
  <DATE>April 1993  </DATE>
  <SHORT_DESCRIPTION name="hex2dec">  conversion représentation hexadécimale vers entier  </SHORT_DESCRIPTION>
  <CALLING_SEQUENCE>
  <CALLING_SEQUENCE_ITEM>d=hex2dec(h)  </CALLING_SEQUENCE_ITEM>
  </CALLING_SEQUENCE>
  <PARAM>
 <PARAM_INDENT>
  <PARAM_ITEM>
  <PARAM_NAME>d  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : matrice d&apos;entiers
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
  <PARAM_ITEM>
  <PARAM_NAME>h  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : matrice de chaînes de caractères contenant les représentations hexadécimales
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
 </PARAM_INDENT>
  </PARAM>
  <DESCRIPTION>
  <P>
    <VERB>hex2dec(x)</VERB> renvoie une matrice d&apos;entiers correspondants aux représentations hexadécimales contenues dans <VERB>x</VERB>.
  </P>
  </DESCRIPTION>
  <EXAMPLE><![CDATA[
hex2dec(['ABC','0','A'])
 ]]></EXAMPLE>
</MAN>

=== clg55/Scilab-Workbench/browsable_source/2.7/Unix/scilab-2.7/man/fr/graphics/xfrect.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?> 
<!DOCTYPE MAN SYSTEM "../../man.dtd">
<MAN>
  <LANGUAGE>fr</LANGUAGE>
  <TITLE>xfrect  </TITLE>
  <TYPE>Scilab Function  </TYPE>
  <DATE>April 1993  </DATE>
  <SHORT_DESCRIPTION name="xfrect"> remplit un rectangle  </SHORT_DESCRIPTION>
  <CALLING_SEQUENCE>
  <CALLING_SEQUENCE_ITEM>xfrect(x,y,w,h)  </CALLING_SEQUENCE_ITEM>
  <CALLING_SEQUENCE_ITEM>xfrect(rect) // rect =[x,y,w,h]  </CALLING_SEQUENCE_ITEM>
  </CALLING_SEQUENCE>
  <PARAM>
 <PARAM_INDENT>
  <PARAM_ITEM>
  <PARAM_NAME>x,y,w,h  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : 4 valeurs réelles définissant le rectangle.
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
 </PARAM_INDENT>
  </PARAM>
  <DESCRIPTION>
  <P>
    <VERB>xrect</VERB> remplit un rectangle défini par <VERB>[x,y,w,h]</VERB> 
    (point en haut à gauche, largeur, hauteur) en utilisant l&apos;échelle courante et la couleur courante.
  </P>
  </DESCRIPTION>
  <EXAMPLE><![CDATA[
plot2d(0,0,-1,"010"," ",[-2,-2,2,2])
xset("color",5)
xfrect(-1,1,2,2)
xset("default")
 ]]></EXAMPLE>
  <SEE_ALSO>
    <SEE_ALSO_ITEM> <LINK>xrect</LINK> </SEE_ALSO_ITEM>     <SEE_ALSO_ITEM> <LINK>xrects</LINK> </SEE_ALSO_ITEM>
  </SEE_ALSO>
  <AUTHOR>J.Ph.C.  </AUTHOR>
</MAN>
