=== clg55/Scilab-Workbench/browsable_source/2.6-en/Unix-Windows/scilab-2.6-en/packages/stixbox-1.2.3/man/man.dtd
<!ELEMENT MAN (META?,LANGUAGE,TITLE,TYPE,DATE,SHORT_DESCRIPTION*,KEYWORD?,CALLING_SEQUENCE?,PARAM*,DESCRIPTION?,ITEMIZE*,EXAMPLE?,SEE_ALSO?,AUTHOR?,BIBLIO?,USED_FUNCTIONS?)>
<!ELEMENT META (#PCDATA)  	 >

<!ATTLIST META 
PATH 	CDATA 	"SCI/" 
CATEGORY 	CDATA 	"ScilabFunction" 	 
VERSION_SCI 	CDATA 	"2.6" 	 
VERSION_DOC 	CDATA 	"1.0" 	 
AUTHOR 	CDATA 	"Matthieu PHILIPPE" 	 
 >

<!ELEMENT LANGUAGE (#PCDATA)  	 >

<!ELEMENT TITLE (#PCDATA)  	 >

<!ELEMENT DATE (#PCDATA)  	 >

<!ELEMENT TYPE (#PCDATA)  	 >

<!ELEMENT KEYWORD (#PCDATA)  	 >

<!ELEMENT SHORT_DESCRIPTION (#PCDATA | P|PP)*  	 >

<!ATTLIST SHORT_DESCRIPTION name CDATA #REQUIRED  	 >

<!ELEMENT USED_FUNCTIONS (#PCDATA)  	 >

<!ELEMENT CALLING_SEQUENCE (#PCDATA|PP|CALLING_SEQUENCE_ITEM)*  	 >

<!ELEMENT PARAM (#PCDATA|PARAM_ITEM|PARAM_INDENT|ITEMIZE|P|TABLE|PP)*  	 >

<!ATTLIST PARAM target (out|in) #IMPLIED  	 >

<!ELEMENT PARAM_ITEM ((PARAM_NAME,PARAM_DESCRIPTION,PARAM_ITEM*)|PARAM_INDENT*)  	 >

<!ELEMENT PARAM_NAME (#PCDATA|VERB)*  	 >

<!ELEMENT PARAM_DESCRIPTION (#PCDATA|P|PP|TABLE|PARAM_INDENT|VERB)*  	 >

<!ELEMENT PARAM_INDENT (#PCDATA|PARAM_ITEM|PARAM_INDENT|P|PP|TABLE|VERB|VERBATIM)*  	 >

<!ELEMENT DESCRIPTION (#PCDATA|P|PP|TABLE|DESCRIPTION_ITEM|VERB|VERBATIM|LINK)*  	 >

<!ELEMENT DESCRIPTION_ITEM (#PCDATA|P|PP|TABLE|ITEMIZE|VERB)*  	 >

<!ATTLIST DESCRIPTION_ITEM label CDATA #IMPLIED  	 >

<!ELEMENT EXAMPLE (#PCDATA)  	 >

<!ELEMENT SEE_ALSO (SEE_ALSO_ITEM)+  	 >

<!ELEMENT AUTHOR (#PCDATA)  	 >

<!ELEMENT BIBLIO (#PCDATA)  	 >

<!ELEMENT CALLING_SEQUENCE_ITEM (#PCDATA)  	 >

<!ELEMENT SEE_ALSO_ITEM (#PCDATA|P|A|LINK)*  	 >

<!ELEMENT A (#PCDATA)*  	 >

<!ATTLIST A href CDATA #REQUIRED  	 >

<!ELEMENT LINK (#PCDATA)*  	 >

<!ELEMENT P (#PCDATA|TABLE|ITEM|EMPTY|VERB|A|LINK)*  	 >

<!ELEMENT VERBATIM (#PCDATA)  	 >

<!ELEMENT ITEM (#PCDATA|TABLE|ITEM|P|VERB)*  	 >

<!ATTLIST ITEM label CDATA #IMPLIED  	 >

<!ELEMENT ITEMIZE (TABLE|ITEM|P|VERBATIM)*  	 >

<!ATTLIST ITEMIZE label CDATA #IMPLIED  	 >

<!ELEMENT TABLE (TABLE_NEW_ROW)+  	 >

<!ELEMENT TABLE_NEW_ROW (TABLE_NEW_COLUMN)+  	 >

<!ELEMENT TABLE_NEW_COLUMN (#PCDATA|VERB)*  	 >

<!ELEMENT MATH (#PCDATA ) 	 >

<!ELEMENT VERB (#PCDATA )>

<!ELEMENT REMARKS (#PCDATA )>

=== clg55/Scilab-Workbench/browsable_source/2.7/Unix/scilab-2.7/man/fr/programming/mode.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?> 
<!DOCTYPE MAN SYSTEM "../../man.dtd">
<MAN>
  <LANGUAGE>fr</LANGUAGE>
  <TITLE>mode  </TITLE>
  <TYPE>Scilab Function  </TYPE>
  <DATE>April 1993  </DATE>
  <SHORT_DESCRIPTION name="mode"> choisit le mode d&apos;exécution des scripts et des fonctions  </SHORT_DESCRIPTION>
  <CALLING_SEQUENCE>
  <CALLING_SEQUENCE_ITEM>mode(k)  </CALLING_SEQUENCE_ITEM>
  <CALLING_SEQUENCE_ITEM>k=mode()   </CALLING_SEQUENCE_ITEM>
  </CALLING_SEQUENCE>
  <DESCRIPTION>
  <P>
    Utilisé <VERB>uniquement</VERB> dans un script ou une fonction, <VERB>mode(k)</VERB> permet de choisir le mode d&apos;affichage utilisé pendant l&apos;exécution, suivant la valeur de <VERB>k</VERB> :
  </P>
 

  <DESCRIPTION_ITEM  label='k=0'> 
    : les nouvelles valeurs des variables sont affichées (voir semi ou comma).
  </DESCRIPTION_ITEM>

  <DESCRIPTION_ITEM  label='k=-1'> 
    : l&apos;exécution est silencieuse (rien n&apos;est affiché : mode par défaut pour les fonctions)
  </DESCRIPTION_ITEM>

  <DESCRIPTION_ITEM  label='k=1 ou k=3'> 
    : les nouvelles valeurs des variables sont affichées, chaque ligne de commande est affichée et précédée de l&apos;invite de commande (mode par défaut pour les scripts lancés par &quot;exec&quot;)
  </DESCRIPTION_ITEM>

  <DESCRIPTION_ITEM  label='k=7'> 
    : les nouvelles valeurs des variables sont affichées, chaque ligne de commande est affichée et précédée de l&apos;invite de commande. L&apos;exécution est interrompue après chaque ligne et reprend après un appui sur la touche entrée/return. 
  </DESCRIPTION_ITEM>
  <P>
    L&apos;affichage est supprimé dans les fonctions compilées (voir getf ou comp).
  </P>
 
  </DESCRIPTION>
  <SEE_ALSO>
    <SEE_ALSO_ITEM> <LINK>exec</LINK> </SEE_ALSO_ITEM>     <SEE_ALSO_ITEM> <LINK>getf</LINK> </SEE_ALSO_ITEM>     <SEE_ALSO_ITEM> <LINK>semi</LINK> </SEE_ALSO_ITEM>     <SEE_ALSO_ITEM> <LINK>comma</LINK> </SEE_ALSO_ITEM>
  </SEE_ALSO>
</MAN>

=== clg55/Scilab-Workbench/browsable_source/2.6-en/Unix-Windows/scilab-2.6-en/packages/stixbox-1.2.3/man/fr/stixbox/qgamma.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?> 
<!DOCTYPE MAN SYSTEM "../../man.dtd">
<MAN>
  <LANGUAGE>eng</LANGUAGE>
  <TITLE>qgamma  </TITLE>
  <TYPE>Stixbox Function  </TYPE>
  <DATE>Nov 2001  </DATE>
  <SHORT_DESCRIPTION name="qgamma"> The gamma inverse distribution function  </SHORT_DESCRIPTION>
  <CALLING_SEQUENCE>
  <CALLING_SEQUENCE_ITEM>x = qgamma(p,a [,s])  </CALLING_SEQUENCE_ITEM>
  </CALLING_SEQUENCE>
  <PARAM>
 <PARAM_INDENT>
  <PARAM_ITEM>
  <PARAM_NAME>p  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : probability
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
  <PARAM_ITEM>
  <PARAM_NAME>a,s  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : positive real, parameter of the gamma distribution (a and scale can be scalar or matrix with common size with p). scale is optional, default value is 1.
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
  <PARAM_ITEM>
  <PARAM_NAME>x  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : inverse of the gamma cumulative distribution function of parameter a at p 
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
 </PARAM_INDENT>
  </PARAM>
  <DESCRIPTION>
  <P>
    The gamma inverse distribution function. The gamma distribution is: 
  </P>
  <VERBATIM><![CDATA[
      s^(a)/Gamma(a) * X^(a-1) * exp(- s*X)
   ]]></VERBATIM>
  </DESCRIPTION>
</MAN>

=== clg55/Scilab-Workbench/browsable_source/2.7/Linux/scilab-2.7/man/eng/functions/library.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?> 
<!DOCTYPE MAN SYSTEM "../../man.dtd">
<MAN>
  <LANGUAGE>eng</LANGUAGE>
  <TITLE>lib  </TITLE>
  <TYPE>Scilab data type  </TYPE>
  <DATE>Nov 2000  </DATE>

  <SHORT_DESCRIPTION name="library"> library datatype description
  </SHORT_DESCRIPTION>
 <CALLING_SEQUENCE>   </CALLING_SEQUENCE>
  <DESCRIPTION>
  <P>
    A library is a data type with type number 14. It contains a path-name
    and a set of names. It allows automatic loading of variables using the
    following algorithm:
  </P>
  <P>
    Suppose the Scilab user references the variable named <VERB>foo</VERB>.
    Scilab first looks if <VERB>foo</VERB> is the name of a primitive or of an
    already defined variable. If not, it looks for <VERB>foo</VERB> sequentially
    (the newest first) in all defined library .
  </P>
  <P>
    Suppose <VERB>foo</VERB> belongs to the set of names of the library <VERB>xlib</VERB>
    then Scilab tries to load the file
    &lt;xlib-path-name&gt;/foo.bin. &lt;xlib-path-name&gt;/foo.bin must have been
    created using the <VERB>save</VERB> function
  </P>
  <P>
    Library are often used for collection of functions, but they can also
    be used for any collection of scilab variables
  </P>
  <P>
    If a function is defined in more than one library, the default search
    algorithm loads thode contained in the newest. It possible to force
    the use of a specific library using dot notation:
  </P>
  <P>
    <VERB>xlib.foo</VERB> loads the variable <VERB>foo</VERB> contained in <VERB>xlib</VERB>.
    if <VERB>foo</VERB> is a function 
    and <VERB>xlib.foo(args)</VERB> executes the functions
  </P>
  <P>
  </P>
  </DESCRIPTION>
  <EXAMPLE><![CDATA[
// elemlib is a predefined library
elemlib //displays the contents of the library
A=rand(3,3);
cosm(A) //loads cosm and executes it

who // now cosm is a variable

elemlib.sinm //loads sinm from the library

elemlib.cosm(A) //reloads cosm and executes it
 ]]></EXAMPLE>
  <SEE_ALSO>
    <SEE_ALSO_ITEM> <LINK>lib</LINK> </SEE_ALSO_ITEM>     <SEE_ALSO_ITEM> <LINK>string</LINK> </SEE_ALSO_ITEM>     <SEE_ALSO_ITEM> <LINK>load</LINK> </SEE_ALSO_ITEM>     <SEE_ALSO_ITEM> <LINK>save</LINK> </SEE_ALSO_ITEM>
  </SEE_ALSO>
</MAN>

=== clg55/Scilab-Workbench/browsable_source/2.6-en/Unix-Windows/scilab-2.6-en/man/fr/elementary/full.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?> 
<!DOCTYPE MAN SYSTEM "../../man.dtd">
<MAN>
  <LANGUAGE>fr</LANGUAGE>
  <TITLE>full  </TITLE>
  <TYPE>Scilab Function  </TYPE>
  <DATE>January 1995  </DATE>
  <SHORT_DESCRIPTION name="full">  conversion d&apos;une matrice creuse en une matrice pleine  </SHORT_DESCRIPTION>
  <CALLING_SEQUENCE>
  <CALLING_SEQUENCE_ITEM>X=full(sp)  </CALLING_SEQUENCE_ITEM>
  </CALLING_SEQUENCE>
  <PARAM>
 <PARAM_INDENT>
  <PARAM_ITEM>
  <PARAM_NAME>sp  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : matrice réelle ou complexe (creuse ou pleine)
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
  <PARAM_ITEM>
  <PARAM_NAME>X  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : matrice pleine
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
 </PARAM_INDENT>
  </PARAM>
  <DESCRIPTION>
  <P>
    <VERB>X=full(sp)</VERB> convertit la matrice creuse <VERB>sp</VERB> en une matrice pleine (si <VERB>sp</VERB> est déjà pleine alors <VERB>X</VERB> est égale à <VERB>sp</VERB>).
  </P>
  </DESCRIPTION>
  <EXAMPLE><![CDATA[
sp=sparse([1,2;5,4;3,1],[1,2,3]);
A=full(sp)
 ]]></EXAMPLE>
  <SEE_ALSO>
    <SEE_ALSO_ITEM> <LINK>sparse</LINK> </SEE_ALSO_ITEM>     <SEE_ALSO_ITEM> <LINK>sprand</LINK> </SEE_ALSO_ITEM>     <SEE_ALSO_ITEM> <LINK>speye</LINK> </SEE_ALSO_ITEM>
  </SEE_ALSO>
</MAN>

=== clg55/Scilab-Workbench/browsable_source/2.7/Linux/scilab-2.7/man/eng/programming/pwd.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?> 
<!DOCTYPE MAN SYSTEM "../../man.dtd">
<MAN>
  <LANGUAGE>eng</LANGUAGE>
  <TITLE>pwd  </TITLE>
  <TYPE>Scilab command  </TYPE>
  <DATE>April 1998  </DATE>
  <SHORT_DESCRIPTION name="pwd"> print Scilab current directory  </SHORT_DESCRIPTION>
  <SHORT_DESCRIPTION name="getcwd"> get Scilab current directory  </SHORT_DESCRIPTION>
  <CALLING_SEQUENCE>
  <CALLING_SEQUENCE_ITEM>pwd  </CALLING_SEQUENCE_ITEM>
  <CALLING_SEQUENCE_ITEM>x=pwd()  </CALLING_SEQUENCE_ITEM>
  <CALLING_SEQUENCE_ITEM>x=getwcd()  </CALLING_SEQUENCE_ITEM>
  </CALLING_SEQUENCE>
  <DESCRIPTION>
  <P>
    <VERB>pwd</VERB> returns in <VERB>ans</VERB> the Scilab current directory.
    <VERB>x=pwd()</VERB> or <VERB>x=getcwd()</VERB> returns in <VERB>x</VERB> the Scilab current
    directory.
  </P>
  <P>
  </P>
  </DESCRIPTION>
  <EXAMPLE><![CDATA[
pwd
x=pwd()
 ]]></EXAMPLE>
  <SEE_ALSO>
    <SEE_ALSO_ITEM> <LINK>chdir</LINK> </SEE_ALSO_ITEM>
  </SEE_ALSO>
</MAN>

=== clg55/Scilab-Workbench/browsable_source/2.7/Linux/scilab-2.7/man/fr/scicos/TIME_f.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?> 
<!DOCTYPE MAN SYSTEM "../../man.dtd">
<MAN>
  <LANGUAGE>eng</LANGUAGE>
  <TITLE>TIME_f  </TITLE>
  <TYPE>Scicos Block  </TYPE>
  <DATE>Janvier 1996  </DATE>
  <SHORT_DESCRIPTION name="TIME_f"> Scicos time generator  </SHORT_DESCRIPTION>
  <DESCRIPTION>
  <P>
    This block is a time generator. The unique regular output is the
    current time.
  </P>
  </DESCRIPTION>
  <ITEMIZE label='DIALOGUE PARAMETERS'>
  <P>
    None.
  </P>
  </ITEMIZE>
</MAN>

=== clg55/Scilab-Workbench/browsable_source/2.7/Linux/scilab-2.7/man/fr/programming/whereis.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?> 
<!DOCTYPE MAN SYSTEM "../../man.dtd">
<MAN>
  <LANGUAGE>fr</LANGUAGE>
  <TITLE>what  </TITLE>
  <TYPE>Scilab Function  </TYPE>
  <DATE>April 1993  </DATE>
  <SHORT_DESCRIPTION name="whereis"> nom de la librairie contenant une fonction  </SHORT_DESCRIPTION>
  <CALLING_SEQUENCE>
  <CALLING_SEQUENCE_ITEM>[librname]=whereis(function-name)  </CALLING_SEQUENCE_ITEM>
  </CALLING_SEQUENCE>
  <DESCRIPTION>
  <P>
    Renvoie une chaîne de caractères contenant le nom de la librairie contenant
    la fonction <VERB>function-name</VERB>. 
    Le chemin d&apos;accès à la librairie peut être obtenu avec la fonction <VERB>&quot;librname&quot;</VERB>.
  </P>
  </DESCRIPTION>
  <SEE_ALSO>
    <SEE_ALSO_ITEM> <LINK>lib</LINK> </SEE_ALSO_ITEM>
  </SEE_ALSO>
</MAN>

=== clg55/Scilab-Workbench/browsable_source/2.7/Unix/scilab-2.7/man/fr/sound/wavread.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?> 
<!DOCTYPE MAN SYSTEM "../../man.dtd">
<MAN>
  <LANGUAGE>eng</LANGUAGE>
  <TITLE>wavread  </TITLE>
  <TYPE>Scilab Function  </TYPE>
  <DATE>April 1993  </DATE>
  <SHORT_DESCRIPTION name="wavread"> load .wav sound file  </SHORT_DESCRIPTION>
  <CALLING_SEQUENCE>
  <CALLING_SEQUENCE_ITEM>y=wavread(wavfile)  </CALLING_SEQUENCE_ITEM>
  <CALLING_SEQUENCE_ITEM>y=wavread(wavfile,ext)  </CALLING_SEQUENCE_ITEM>
  <CALLING_SEQUENCE_ITEM>[y,Fs,bits]=wavread(wavfile)  </CALLING_SEQUENCE_ITEM>
  <CALLING_SEQUENCE_ITEM>[y,Fs,bits]=wavread(wavfile,ext)  </CALLING_SEQUENCE_ITEM>
  </CALLING_SEQUENCE>
  <PARAM>
 <PARAM_INDENT>
  <PARAM_ITEM>
  <PARAM_NAME>wavfile  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : string (The .wav extension is appended if no extension is given)
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
  <PARAM_ITEM>
  <PARAM_NAME>Fs  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : integer, frequency sampling in Hz.
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
  <PARAM_ITEM>
  <PARAM_NAME>ext  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : string (<VERB>&apos;size&apos;</VERB>) or integer (to read n samples) or 1 x 2 integer vector [n1,n2] (to read from n1 to n2).
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
 </PARAM_INDENT>
  </PARAM>
  <DESCRIPTION>
  <P>
    Utility function to read <VERB>.wav</VERB> sound file.
    <VERB>wavread(wavfile)</VERB> loads a sound file specified by the string wavfile,
    returning the sampled data in y. Amplitude values are in the range [-1,+1].
    Supports multi-channel data in the following formats:
    8-bit mu-law, 8-, 16-, and 32-bit linear, and floating point.
  </P>
  <P>
    <VERB>[y,Fs,bits]=wavread(wavfile)</VERB> returns the sample rate (Fs) in Hertz
    and the number of bits per sample used to encode the data in the file.
  </P>
  <P>
    <VERB>wavread(wavfile,n)</VERB> returns the first n samples from each channel.
  </P>
  <P>
    <VERB>wavread(wavfile,[n1,n2])</VERB> returns samples n1 to n2.
  </P>
  <P>
    <VERB>read(wavfile,&apos;size&apos;)</VERB> returns the size of the audio data contained
    in the file in place of the actual audio data, returning the
    vector as [samples channels].
  </P>
  </DESCRIPTION>
  <SEE_ALSO>
    <SEE_ALSO_ITEM> <LINK>auread</LINK> </SEE_ALSO_ITEM>     <SEE_ALSO_ITEM> <LINK>savewave</LINK> </SEE_ALSO_ITEM>     <SEE_ALSO_ITEM> <LINK>analyze</LINK> </SEE_ALSO_ITEM>     <SEE_ALSO_ITEM> <LINK>mapsound</LINK> </SEE_ALSO_ITEM>
  </SEE_ALSO>
</MAN>
