=== clg55/Scilab-Workbench/browsable_source/2.6-en/Unix-Windows/scilab-2.6-en/packages/stixbox-1.2.3/man/man.dtd
<!ELEMENT MAN (META?,LANGUAGE,TITLE,TYPE,DATE,SHORT_DESCRIPTION*,KEYWORD?,CALLING_SEQUENCE?,PARAM*,DESCRIPTION?,ITEMIZE*,EXAMPLE?,SEE_ALSO?,AUTHOR?,BIBLIO?,USED_FUNCTIONS?)>
<!ELEMENT META (#PCDATA)  	 >

<!ATTLIST META 
PATH 	CDATA 	"SCI/" 
CATEGORY 	CDATA 	"ScilabFunction" 	 
VERSION_SCI 	CDATA 	"2.6" 	 
VERSION_DOC 	CDATA 	"1.0" 	 
AUTHOR 	CDATA 	"Matthieu PHILIPPE" 	 
 >

<!ELEMENT LANGUAGE (#PCDATA)  	 >

<!ELEMENT TITLE (#PCDATA)  	 >

<!ELEMENT DATE (#PCDATA)  	 >

<!ELEMENT TYPE (#PCDATA)  	 >

<!ELEMENT KEYWORD (#PCDATA)  	 >

<!ELEMENT SHORT_DESCRIPTION (#PCDATA | P|PP)*  	 >

<!ATTLIST SHORT_DESCRIPTION name CDATA #REQUIRED  	 >

<!ELEMENT USED_FUNCTIONS (#PCDATA)  	 >

<!ELEMENT CALLING_SEQUENCE (#PCDATA|PP|CALLING_SEQUENCE_ITEM)*  	 >

<!ELEMENT PARAM (#PCDATA|PARAM_ITEM|PARAM_INDENT|ITEMIZE|P|TABLE|PP)*  	 >

<!ATTLIST PARAM target (out|in) #IMPLIED  	 >

<!ELEMENT PARAM_ITEM ((PARAM_NAME,PARAM_DESCRIPTION,PARAM_ITEM*)|PARAM_INDENT*)  	 >

<!ELEMENT PARAM_NAME (#PCDATA|VERB)*  	 >

<!ELEMENT PARAM_DESCRIPTION (#PCDATA|P|PP|TABLE|PARAM_INDENT|VERB)*  	 >

<!ELEMENT PARAM_INDENT (#PCDATA|PARAM_ITEM|PARAM_INDENT|P|PP|TABLE|VERB|VERBATIM)*  	 >

<!ELEMENT DESCRIPTION (#PCDATA|P|PP|TABLE|DESCRIPTION_ITEM|VERB|VERBATIM|LINK)*  	 >

<!ELEMENT DESCRIPTION_ITEM (#PCDATA|P|PP|TABLE|ITEMIZE|VERB)*  	 >

<!ATTLIST DESCRIPTION_ITEM label CDATA #IMPLIED  	 >

<!ELEMENT EXAMPLE (#PCDATA)  	 >

<!ELEMENT SEE_ALSO (SEE_ALSO_ITEM)+  	 >

<!ELEMENT AUTHOR (#PCDATA)  	 >

<!ELEMENT BIBLIO (#PCDATA)  	 >

<!ELEMENT CALLING_SEQUENCE_ITEM (#PCDATA)  	 >

<!ELEMENT SEE_ALSO_ITEM (#PCDATA|P|A|LINK)*  	 >

<!ELEMENT A (#PCDATA)*  	 >

<!ATTLIST A href CDATA #REQUIRED  	 >

<!ELEMENT LINK (#PCDATA)*  	 >

<!ELEMENT P (#PCDATA|TABLE|ITEM|EMPTY|VERB|A|LINK)*  	 >

<!ELEMENT VERBATIM (#PCDATA)  	 >

<!ELEMENT ITEM (#PCDATA|TABLE|ITEM|P|VERB)*  	 >

<!ATTLIST ITEM label CDATA #IMPLIED  	 >

<!ELEMENT ITEMIZE (TABLE|ITEM|P|VERBATIM)*  	 >

<!ATTLIST ITEMIZE label CDATA #IMPLIED  	 >

<!ELEMENT TABLE (TABLE_NEW_ROW)+  	 >

<!ELEMENT TABLE_NEW_ROW (TABLE_NEW_COLUMN)+  	 >

<!ELEMENT TABLE_NEW_COLUMN (#PCDATA|VERB)*  	 >

<!ELEMENT MATH (#PCDATA ) 	 >

<!ELEMENT VERB (#PCDATA )>

<!ELEMENT REMARKS (#PCDATA )>

=== clg55/Scilab-Workbench/browsable_source/2.6-en/Unix-Windows/scilab-2.6-en/man/eng/control/equil.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?> 
<!DOCTYPE MAN SYSTEM "../../man.dtd">
<MAN>
  <LANGUAGE>eng</LANGUAGE>
  <TITLE>equil  </TITLE>
  <TYPE>Scilab Function  </TYPE>
  <DATE>April 1993  </DATE>
  <SHORT_DESCRIPTION name="equil"> balancing of pair of symmetric matrices  </SHORT_DESCRIPTION>
  <CALLING_SEQUENCE>
  <CALLING_SEQUENCE_ITEM>T=equil(P,Q)  </CALLING_SEQUENCE_ITEM>
  </CALLING_SEQUENCE>
  <PARAM>
 <PARAM_INDENT>
  <PARAM_ITEM>
  <PARAM_NAME>P, Q  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : two positive definite symmetric matrices
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
  <PARAM_ITEM>
  <PARAM_NAME>T  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : nonsingular matrix
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
 </PARAM_INDENT>
  </PARAM>
  <DESCRIPTION>
  <P>
    <VERB>equil</VERB> returns <VERB>t</VERB> such that:
  </P>
  <P>
    <VERB>T*P*T&apos;</VERB> and  <VERB>inv(T)&apos;*Q*inv(T)</VERB>  are both equal to a same 
    diagonal and positive matrix.
  </P>
  </DESCRIPTION>
  <EXAMPLE><![CDATA[
P=rand(4,4);P=P*P';
Q=rand(4,4);Q=Q*Q';
T=equil(P,Q)
clean(T*P*T')
clean(inv(T)'*Q*inv(T))
 ]]></EXAMPLE>
  <SEE_ALSO>
    <SEE_ALSO_ITEM> <LINK>equil1</LINK> </SEE_ALSO_ITEM>     <SEE_ALSO_ITEM> <LINK>balanc</LINK> </SEE_ALSO_ITEM>     <SEE_ALSO_ITEM> <LINK>ctr_gram</LINK> </SEE_ALSO_ITEM>
  </SEE_ALSO>
</MAN>

=== clg55/Scilab-Workbench/browsable_source/2.6-en/Unix-Windows/scilab-2.6-en/man/eng/utilities/language.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?> 
<!DOCTYPE MAN SYSTEM "../../man.dtd">
<MAN>
  <LANGUAGE>eng</LANGUAGE>
  <TITLE>LANGUAGE</TITLE>
  <TYPE>Scilab Variable</TYPE>
  <DATE>January 2002 </DATE>
  <SHORT_DESCRIPTION name="LANGUAGE"> Variable defining the language  </SHORT_DESCRIPTION>
  <DESCRIPTION>
  <P>
    The global variable <VERB>LANGUAGE</VERB> is a string.  It defines
    the language to use for the on-line help and various menus.  At
    the present time, the values of <VERB>LANGUAGE</VERB> can be
    <VERB>"eng"</VERB> for English, which is the default, or
    <VERB>"fr"</VERB> for French.
  </P>
  <P>
    This variable is defined in the startup file
    <VERB>scilab.star</VERB>. It can be changed there.
  </P>
  <P>
    When launching Scilab, you can also give the value of language
    as an argument: <VERB>scilab -l &lt;language&gt;</VERB> for Unix and
    <VERB>runscilab.exe -l &lt;language&gt;</VERB> for Windows.
  </P>
  </DESCRIPTION>
</MAN>

=== clg55/Scilab-Workbench/browsable_source/2.6-en/Unix-Windows/scilab-2.6-en/man/eng/metanet/chain_struct.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?> 
<!DOCTYPE MAN SYSTEM "../../man.dtd">
<MAN>
  <LANGUAGE>eng</LANGUAGE>
  <TITLE>chain_struct  </TITLE>
  <TYPE>Scilab function  </TYPE>
  <DATE>September 1996  </DATE>
  <SHORT_DESCRIPTION name="chain_struct"> chained structure from adjacency lists of a graph  </SHORT_DESCRIPTION>
  <CALLING_SEQUENCE>
  <CALLING_SEQUENCE_ITEM>[fe,che,fn,chn] = chain_struct(g)  </CALLING_SEQUENCE_ITEM>
  <CALLING_SEQUENCE_ITEM>[fe,che,fn,chn] = chain_struct(lp,la,ls)  </CALLING_SEQUENCE_ITEM>
  </CALLING_SEQUENCE>
  <PARAM>
 <PARAM_INDENT>
  <PARAM_ITEM>
  <PARAM_NAME>g  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : graph list
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
  <PARAM_ITEM>
  <PARAM_NAME>lp  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : row vector, pointer array of the adjacency lists description of the graph  (its size is the number of nodes of the graph + 1) 
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
  <PARAM_ITEM>
  <PARAM_NAME>la  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : row vector, arc array of the adjacency lists description of the graph  (its size is the number of edges of the graph) 
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
  <PARAM_ITEM>
  <PARAM_NAME>ls  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : row vector, node array of the adjacency lists description of the graph  (its size is the number of edges of the graph) 
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
  <PARAM_ITEM>
  <PARAM_NAME>fe  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : row vector of the numbers of the first edges starting from nodes (its size is the number of nodes of the graph)
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
  <PARAM_ITEM>
  <PARAM_NAME>che  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : row vector of the numbers of the chained edges  (its size is the number of edges of the graph)
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
  <PARAM_ITEM>
  <PARAM_NAME>fn  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : row vector of the numbers of the first nodes reached by the edges of  <VERB>fe</VERB> (its size is the number of nodes of the graph)
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
  <PARAM_ITEM>
  <PARAM_NAME>chn  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : row vector of the nodes reached by the edges of <VERB>che</VERB>
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
 </PARAM_INDENT>
  </PARAM>
  <DESCRIPTION>
  <P>
    <VERB>chain_struct</VERB> computes the row vectors of the edge chained structure 
    description of the graph <VERB>g</VERB>.
    It is also possible to give directly <VERB>chain_struct</VERB> the adjacency lists of
    the graph. This is more efficient if the adjacency lists are already
    available since <VERB>chain_struct</VERB> uses them to make computations.
  </P>
  <P>
    The vectors <VERB>fe</VERB>, <VERB>che</VERB>, <VERB>fn</VERB> and <VERB>chn</VERB> describe the
    chained structure in the following way:
  </P>
  <P>
    <VERB>fe(i))</VERB> is the number of the first edge starting from node i
  </P>
  <P>
    <VERB>che(fe(i))</VERB> is the number of the second edge starting from
    node i, <VERB>che(che(fe(i)))</VERB> is the number of the third edge starting from
    node i and so on until the value is 0
  </P>
  <P>
    <VERB>fn(i)</VERB> is the number of the first node reached from node i
  </P>
  <P>
    <VERB>ch(i)</VERB> is the number of the node reached by edge <VERB>che(i)</VERB>.
  </P>
  </DESCRIPTION>
  <EXAMPLE><![CDATA[
ta=[1 1 2 3 5 4 6 7 7 3 3 8 8 5];
he=[2 3 5 4 6 6 7 4 3 2 8 1 7 4];
g=make_graph('foo',1,8,ta,he);
g('node_x')=[116 231 192 323 354 454 305 155];
g('node_y')=[118 116 212 219 117 185 334 316];
show_graph(g);
[fe,che,fn,chn] = chain_struct(g)
 ]]></EXAMPLE>
  <SEE_ALSO>
    <SEE_ALSO_ITEM> <LINK>adj_lists</LINK> </SEE_ALSO_ITEM>     <SEE_ALSO_ITEM> <LINK>graph_2_mat</LINK> </SEE_ALSO_ITEM>
  </SEE_ALSO>
</MAN>

=== clg55/Scilab-Workbench/browsable_source/2.6-en/Unix-Windows/scilab-2.6-en/packages/stixbox-1.2.3/man/fr/stixbox/erfinv.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?> 
<!DOCTYPE MAN SYSTEM "../../man.dtd">
<MAN>
  <LANGUAGE>eng</LANGUAGE>
  <TITLE>erfinv  </TITLE>
  <TYPE>Stixbox Function  </TYPE>
  <DATE>Nov 2001  </DATE>
  <SHORT_DESCRIPTION name="erfinv"> Inverse of the error function  </SHORT_DESCRIPTION>
  <CALLING_SEQUENCE>
  <CALLING_SEQUENCE_ITEM>x = erfinv(y)  </CALLING_SEQUENCE_ITEM>
  </CALLING_SEQUENCE>
  <PARAM>
 <PARAM_INDENT>
  <PARAM_ITEM>
  <PARAM_NAME>x,y  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : two matrices or vectors.
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
 </PARAM_INDENT>
  </PARAM>
  <DESCRIPTION>
  <P>
    Inverse of the error function. x = erfinv(y) satisfies y = erf(x),
        -1 &lt;= y &lt; 1, -inf &lt;= x &lt;= inf.
  </P>
  <P>
  </P>
  </DESCRIPTION>
</MAN>

=== clg55/Scilab-Workbench/browsable_source/2.6-en/Unix-Windows/scilab-2.6-en/packages/stixbox-1.2.3/man/eng/stixbox/datas15.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?> 
<!DOCTYPE MAN SYSTEM "../../man.dtd">
<MAN>
  <LANGUAGE>eng</LANGUAGE>
  <TITLE>datas15  </TITLE>
  <TYPE>Stixbox Function  </TYPE>
  <DATE>Nov 2001  </DATE>
  <SHORT_DESCRIPTION name="datas15"> turnover datas  </SHORT_DESCRIPTION>
  <CALLING_SEQUENCE>
  <CALLING_SEQUENCE_ITEM>x=datas15()  </CALLING_SEQUENCE_ITEM>
  </CALLING_SEQUENCE>
  <DESCRIPTION>
  <VERBATIM><![CDATA[
Source: J-P Lecoutre, S. Legait-Maille, Ph. Tassi (1990),
   "statistique, exercices corriges avec rappels de 
  cours", Masson.

Pris:         source

Dimensions: 11 observations de  3 variables

Description: Le chiffre d'affaire en millions de francs (2eme colonne)
               et le nombre de salaries en milliers (1ere colonne) d'un
               un secteur industriel pour chaque annee de 1957 a 1967 
               (1ere colonne) 

   ]]></VERBATIM>
  </DESCRIPTION>
</MAN>

=== clg55/Scilab-Workbench/browsable_source/2.7/Linux/scilab-2.7/man/fr/elementary/trisolve.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?> 
<!DOCTYPE MAN SYSTEM "../../man.dtd">
<MAN>
  <LANGUAGE>fr</LANGUAGE>
  <TITLE>trisolve  </TITLE>
  <TYPE>Scilab Function  </TYPE>
  <DATE>April 1993  </DATE>
  <SHORT_DESCRIPTION name="trisolve"> solveur symbolique de système linéaire  </SHORT_DESCRIPTION>
  <CALLING_SEQUENCE>
  <CALLING_SEQUENCE_ITEM>[x [,sexp]] = trisolve(A,b [,sexp])  </CALLING_SEQUENCE_ITEM>
  </CALLING_SEQUENCE>
  <PARAM>
 <PARAM_INDENT>
  <PARAM_ITEM>
  <PARAM_NAME>A,b,x  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : matrices (resp. vecteurs) de chaînes de caractères
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
 </PARAM_INDENT>
  </PARAM>
  <DESCRIPTION>
  <P>
    Résout <VERB>A*x = b</VERB> quand <VERB>A</VERB> est une matrice triangulaire supérieure de chaînes de caractères.
  </P>
  <P>
    <VERB>sexp</VERB> est un ensemble d&apos;expressions communes dans <VERB>A</VERB>, <VERB>b</VERB> et <VERB>x</VERB>.
  </P>
  </DESCRIPTION>
  <EXAMPLE><![CDATA[
A=['x','y';'0','z'];b=['0';'1'];
w=trisolve(A,b)
x=5;y=2;z=4;
evstr(w)
inv(evstr(A))*evstr(b)
 ]]></EXAMPLE>
  <SEE_ALSO>
    <SEE_ALSO_ITEM> <LINK>trianfml</LINK> </SEE_ALSO_ITEM>     <SEE_ALSO_ITEM> <LINK>solve</LINK> </SEE_ALSO_ITEM>
  </SEE_ALSO>
  <AUTHOR>F.D, S.S  </AUTHOR>
</MAN>

=== clg55/Scilab-Workbench/browsable_source/2.6-en/Unix-Windows/scilab-2.6-en/man/fr/elementary/unique.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?> 
<!DOCTYPE MAN SYSTEM "../../man.dtd">
<MAN>
  <LANGUAGE>fr</LANGUAGE>
  <TITLE>unique  </TITLE>
  <TYPE>Scilab Function  </TYPE>
  <DATE>April 1999  </DATE>
  <SHORT_DESCRIPTION name="unique"> extrait les composantes distinctes d&apos;un vecteur  </SHORT_DESCRIPTION>
  <CALLING_SEQUENCE>
  <CALLING_SEQUENCE_ITEM>[N, [k]]=unique(M)  </CALLING_SEQUENCE_ITEM>
  <CALLING_SEQUENCE_ITEM>  </CALLING_SEQUENCE_ITEM>
  </CALLING_SEQUENCE>
  <PARAM>
 <PARAM_INDENT>
  <PARAM_ITEM>
  <PARAM_NAME>M,N  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : vecteur réel ou vecteur de chaînes de caractères
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
  <PARAM_ITEM>
  <PARAM_NAME>k  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : vecteur d&apos;entiers
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
 </PARAM_INDENT>
  </PARAM>
  <DESCRIPTION>
  <P>
    <VERB>unique(M)</VERB> renvoie un vecteur contenant les valeurs distinctes contenues dans les termes de <VERB>M</VERB> classées par ordre croissant.
  </P>
  <P>
    S&apos;il est présent l&apos;argument de sortie <VERB>k</VERB> contient la position de la première occurrence de chaque valeur distincte dans <VERB>M</VERB>.
  </P>
  <P>
  </P>
  </DESCRIPTION>
  <EXAMPLE><![CDATA[
M=round(2*rand(20,1));

unique(M)
[N,k]=unique(M)

unique(string(M))
[N,k]=unique(string(M))

 ]]></EXAMPLE>
  <SEE_ALSO>
    <SEE_ALSO_ITEM> <LINK>union</LINK> </SEE_ALSO_ITEM>     <SEE_ALSO_ITEM> <LINK>sort</LINK> </SEE_ALSO_ITEM>     <SEE_ALSO_ITEM> <LINK>lex_sort</LINK> </SEE_ALSO_ITEM>
  </SEE_ALSO>
</MAN>

=== clg55/Scilab-Workbench/browsable_source/2.7/Unix/scilab-2.7/man/fr/scicos/scicos_link.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?> 
<!DOCTYPE MAN SYSTEM "../../man.dtd">
<MAN>
  <LANGUAGE>eng</LANGUAGE>
  <TITLE>scicos_link  </TITLE>
  <TYPE>Scicos data structure  </TYPE>
  <DATE>Janvier 2003  </DATE>
  <SHORT_DESCRIPTION name="scicos_link"> Scicos link data structure  </SHORT_DESCRIPTION>
  <ITEMIZE label='DEFINITION'>
  <VERBATIM><![CDATA[
lnk=mlist(['Link','xx','yy','id','thick','ct','from','to'],..
     xx,yy,id,thick,ct,from,to)

   ]]></VERBATIM>
  <ITEM label='lnk: Scilab mlist, Scicos link data structure defined by the formal'>
name &apos;Link&apos; and containing the following fields:

  </ITEM>
  </ITEMIZE>
  <ITEMIZE label='FIELDS'>
  <ITEM label='xx'>
: vector of x coordinates of the link path.

  </ITEM>
  <ITEM label='yy'>
: vector of y coordinates of the link path.

  </ITEM>
  <ITEM label='id'>
: character string, the link identification, default value is <VERB>&apos;drawlink&apos;.</VERB>

  </ITEM>
  <ITEM label='thick'>
: 2 x 1 vector, for definition of the thickness of the link, default value is <VERB>[0,0].</VERB>

  </ITEM>
  <ITEM label='ct'>
: 2 x 1 vector, <VERB>[color,typ]</VERB> where <VERB>color</VERB> defines the color used for the link drawing and <VERB>typ</VERB> defines its type (0 for regular link ,1 for event link).

  </ITEM>
  <ITEM label='from'>
: 2 x 1 vector, <VERB>[block,port]</VERB> where <VERB>block</VERB> is the index of the block at the origin of the link and <VERB>port</VERB> is the index of the port.

  </ITEM>
  <ITEM label='to'>
: 2 x 1 vector, <VERB>[block,port]</VERB> where <VERB>block</VERB> is the index of the block at the end of the link and <VERB>port</VERB> is the index of the port.

  </ITEM>
  </ITEMIZE>
  <DESCRIPTION>
  <P>
    Scicos editor creates and uses for each link a data structure
    containing all information relative to the graphic interface and
    interconnection information. Each of them are stored in the Scicos
    editor diagram data structure. Index of these in Scicos
    editor diagram data structure is given by the creation order.
  </P>
  </DESCRIPTION>
  <SEE_ALSO>
    <SEE_ALSO_ITEM> <LINK>scicos_block</LINK> </SEE_ALSO_ITEM>     <SEE_ALSO_ITEM> <LINK>scicos_graphics</LINK> </SEE_ALSO_ITEM>     <SEE_ALSO_ITEM> <LINK>scicos_model</LINK> </SEE_ALSO_ITEM>     <SEE_ALSO_ITEM> <LINK>scicos_diagram</LINK> </SEE_ALSO_ITEM>
  </SEE_ALSO>
</MAN>
